# Generated by Django 4.1.5 on 2023-03-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="snippet",
            table="content",
        ),
    ]
