# Generated by Django 4.1.5 on 2023-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_alter_snippet_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="snippet",
            table=None,
        ),
    ]
